
// Generated by slyft.io
// This code part has been generated on an "as is" basis, without warranties or conditions of any kind.

// application-part header



    #include "Arduino.h"

#include "microcoap/coap.h"

// include data structure headers
#include "digital.h"

// struct TUT1__digital
#include "digital.h"



//
// CoAP Application level handlers
//

// -- POST  /digital

struct TUT1__coapled__post___digital_req {
    struct {

        struct TUT1__digital  digital;

    } data;
};

struct TUT1__coapled__post___digital_resp {
    coap_responsecode_t  response_code;
    struct {

  
        // data struct for response code 205
        struct TUT1__digital  digital_205;

    } data;
};

// -- Application level handler for POST to /digital
bool TUT1__coapled__post___digital(
    struct TUT1__coapled__post___digital_req *req,
    struct TUT1__coapled__post___digital_resp *resp);


